[package]
name = "pwned"
version = "0.1.0"
authors = ["Joao Veiga <joao@fishbrain.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
log = "0.4.11"
minreq = { version = "2.2.1", features = ["https-rustls"] }
sha = "1.0"
eyre = "0.6.0"
color-eyre = "0.5.4"
prettytable-rs = "0.8.0"
